articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

# /articles/ ___
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    # /articles/3/comments/
    path('<int:article_pk>/comments/', views.comment_create, name='comments_create'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # /articles/ 로 들어왔다면 articles/urls.py 로 이동해
    path('jobs/', include('jobs.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

# /articles/ ___
urlpatterns = [
    path('', views.index, name='index'),
    path('past_job/', views.past_job, name='past_job'),
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    # on_delete=models.CASCADE == 'Article이 삭제되면 Comment도 함께 삭제'
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #마지막에 생성된 댓글부터 역순으로 가져오게함
    class Meta:
    
        ordering = ['-pk']

    def __str__(self):
        return self.content

jobs/models.py
from django.db import models

# Create your models here.

class Job(models.Model):
    name = models.CharField(max_length=20)
    past_job = models.TextField()

    def __str__(self):
        return self.name

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment


# articles 의 메인 페이지, article list 를 보여 줌
def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)


# Variable Routing 으로 사용자가 보기를 원하는 페이지 pk 를 받아서
# Detail 페이지를 보여준다.
def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comment_set.all()

    context = {'article': article, 'comments':comments}

    return render(request, 'articles/detail.html', context)


# 데이터를 전달 받아서 article 생성
def create(request):
    # 만약 POST 요청일 경우 사용자 데이터 받아서 article 생성
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        article = Article()
        article.title = title
        article.content = content
        article.save()
        return redirect('articles:detail', article.pk)
    # 만약 GET 요청으로 들어오면 html 페이지 rendering
    else:
        return render(request, 'articles/create.html')


# 사용자로부터 받은 article_pk 값에 해당하는 article 을 삭제한다.
def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', article_pk=article_pk)


# /articles/5/update/
def update(request, article_pk):
    # POST /articles/5/update/ : 실제 Update 로직이 수행
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        article.title = title
        article.content = content
        article.save()
        return redirect('articles:detail', article.pk)

    # GET /articles/5/update/ : Update 를 하기위한 Form 을 제공하는 페이지
    else:
        context = {'article': article}
        return render(request, 'articles/update.html', context)

def comment_create(request, article_pk):
    # article_pk 에 해당하는 article 에 새로운 comment 생성
    # 생성한 다음 detail page로 redirect
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        content = request.POST.get('content')
        comment = Comment(article=article, content=content)
        comment.save()
    
    return redirect('articles:detail', article.pk)
    

jobs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Job
from faker import Faker
import requests
from pprint import pprint

# Create your views here.
fake = Faker('ko_KR')
def past_job(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        
        temp = Job.objects.filter(name=name)
        if not temp :
            job = Job()
            job.name = name
            job.past_job = fake.job()
            job.save()
        
        else:
            job = get_object_or_404(Job, name=name)
        job_name = job.past_job.split()[-1]
        url = f'https://api.giphy.com/v1/gifs/search?api_key=KL6K2v0CUvZrECUq4d9dIJnSBuZgtRgf&q={job_name}&limit=1'
        data = requests.get(url).json()
        if data['data']:
            image = data['data'][0]['images']['downsized_medium']['url']
        else:
            image = 'https://pbs.twimg.com/profile_images/770139154898382848/ndFg-IDH_400x400.jpg'

        context = {
                'name':job.name,
                'job':job.past_job,
                'image':image
            }
        return render(request, 'jobs/past_job.html', context)
    else:
        redirect('jobs:index')


        

def index(request):
    return render(request, 'jobs/index.html')

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}New Article{% endblock title %}

{% block body %}
  <h1>New Article</h1>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="title"><br>
    <textarea name="content" cols="30" rows="10"></textarea><br>
    <button type="submit">생성하기</button>
  </form>
  <a href="{% url 'articles:index' %}">[뒤로가기]</a>
{% endblock body %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}Article Detail{% endblock title %}

{% block body %}
  <h1>{{ article.title }}</h1>
  <p>작성일자: {{ article.created_at }}</p>
  <hr>
  <h4>comments</h4>
  {% comment %} 댓글 작성을 위한 form {% endcomment %}
  <form action="{% url 'articles:comments_create' article.pk %}" method="post">
  {% csrf_token %}
  <input type="text" name="content">
  <button type="submint">댓글 작성</button>
  </form>
  {% for comment in comments %}
  <li>{{ comment.content }}</li>
  {% empty %}
  <p>아직 댓글이 없습니다.</p>
  {% endfor %}
  <hr>
  <p>{{ article.content }}</p>
  <a href="{% url 'articles:index' %}">[뒤로가기]</a>
  <a href="{% url 'articles:update' article.pk %}">[수정하기]</a>
  <form action="{% url 'articles:delete' article.pk %}" method="POST" onclick="return confirm('Are you sure?')">
    {% csrf_token %}
    <button type="submit">삭제하기</button>
  </form>
{% endblock body %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block title %}Articles{% endblock title %}

{% block body %}
  <h1>Articles</h1>
  <a href="{% url 'articles:create' %}">[작성하기]</a>
  <hr>
  {% for article in articles %}
  <div>
    <h3><a href="{% url 'articles:detail' article.pk %}">{{ article.pk }}. {{ article.title }}</a></h3>
    <p>{{ article.content }}</p>
  </div>
  <br>
  {% endfor %}
{% endblock body %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block title %}Update Article{% endblock title %}

{% block body %}
<h1>Update Article</h1>
<form action="{% url 'articles:update' article.pk %}" method="POST">
  {% csrf_token %}
  <input type="text" name="title" value="{{ article.title }}"><br>
  <textarea name="content" cols="30" rows="10">{{ article.content }}</textarea><br>
  <button type="submit">수정하기</button>
</form>
{% endblock body %}

crud/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
  {% block body %}
  {% endblock body %}
</body>
</html>

jobs/templates/jobs/index.html
{% extends 'base.html' %}

{% block title %}Name search{% endblock title %}

{% block body %}
<form action="{% url 'jobs:past_job' %}" method="post">
{% csrf_token %}
<p>Name:</p><input type="text" name='name'>
<button type="submit">제출하기</button>
</form>
{% endblock body %}

jobs/templates/jobs/past_job.html
{% extends 'base.html' %}
{% block title %}
your job
{% endblock title %}

{% block body %}
<h1>너의 직업은</h1>
<h3>{{ name }}의 전생직업은 {{ job }} 이었습니다</h3>
<img src={{image}} alt="놉">
<a href="/jobs">[돌아가기]</a>
{% endblock body %}